In [ ]:
import numpy as np
import matplotlib as mp

In [ ]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data)
print(data + data)

In [ ]:
points = np.arange(-5, 5 , 0.01)
print(points)
xs, ys = np.meshgrid(points, points)
print(ys)

In [ ]:
arr = np.standard_normal((5,4))
print(arr)

In [ ]:
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

# array[start:end:step]
print(array[:,1])
print(array[0:2, 0:2])
print(array[0:2,2:4])
print(array[2:4, 2:4])
print(array[2:4, 0:2])



In [25]:
arrvect = np.array([1, 2, 3, 4], dtype=int)
print(np.sqrt(arrvect))
print(arrvect ** 2 * np.pi)

[1.         1.41421356 1.73205081 2.        ]
[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [29]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 ** array2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[    1    64  2187 65536]


In [38]:
scores = np.array([91,55, 100, 73, 82, 64])
print(scores == 100)
print(scores >= 60)

print(scores[scores < 60])



[False False  True False False False]
[ True False  True  True  True  True]
[55]


In [50]:
arragre = np.random.default_rng().integers(1, 50, size=(4, 6))

print(arragre)
print(np.sum(arragre))
print(np.mean(arragre))
print(np.std(arragre))
print(np.var(arragre))
print(np.min(arragre))
 

[[28 33 17 27 30 43]
 [ 1  7 46 10 28  6]
 [44 11 27 37 34  5]
 [38 27 34 13 27 35]]
608
25.333333333333332
13.088374824841912
171.30555555555557
1
