In [ ]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import ast as ast
from IPython.display import HTML

In [ ]:
bosses = pd.read_csv("./datasets/bosses.csv")

bosses = bosses.drop(columns=["description"])

In [ ]:
def path_to_image_html(path):
    return f'<img src = {path} width = 80 height = 40 style = "object-fit: cover;"/>'

HTML(bosses.to_html(escape=False, formatters={'image': path_to_image_html}))

In [ ]:
bosses.describe()

In [ ]:
bosses["healthPoints"] = pd.to_numeric(bosses["healthPoints"], errors="coerce")

In [ ]:
bosses

In [ ]:
bosses["healthPoints"].describe()

In [ ]:
print(bosses["healthPoints"].isnull().sum())

In [ ]:
bosses["healthPoints"] = bosses["healthPoints"].fillna(2000)

In [ ]:
bosses["healthPoints"]

In [ ]:
HTML(bosses.to_html(escape=False, formatters={'image': path_to_image_html}))

In [ ]:

bosses.loc[bosses["healthPoints"].idxmax(), "name"]

In [ ]:

bosses.loc[bosses["healthPoints"].idxmin(), "name"]

In [ ]:
average_health_points = bosses["healthPoints"].mean()

In [ ]:
bosses["healthPoints"].median()


[10 20 30 40]
[[1 2 3]
 [4 5 6]]
